### ISSUE TITLE
Typo error in CONTRIBUTING.md

### ISSUE THREAD

**Issue by Neeltyper001** [BoboPlastic/LandingPages#1]
Hey ! I want to fix a typo error in CONTRIBUTING.md can you just assign it to me ?

**Comment by BoboPlastic** [comment]
Yeah, you're welcome to do so !

**Comment by BoboPlastic** [comment]
> Hey ! I want to fix a typo error in CONTRIBUTING.md can you just assign it to me ?

Yeah, you are welcome to do so!

**Comment by Neeltyper001** [comment]
> > Hey ! I want to fix a typo error in CONTRIBUTING.md can you just assign it to me ?
> 
> Yeah, you are welcome to do so!

Thanks
