### ISSUE TITLE
want to add animated Landing page using simple HTML , CSS , Javascript 

### ISSUE THREAD

**Issue by pra9patil** [BoboPlastic/LandingPages#7]
Hey @BoboPlastic sir 
I like your repo and idea 
I have an amazing landing page with some css animation in it 
Will you please assign mi this issue so I can work on it and add it to your repo with readme.md file 

Thank you

**Comment by BoboPlastic** [comment]
Yeah sure, it would be great to have your amazing contribution !

**Comment by BoboPlastic** [comment]
> Hey @BoboPlastic sir I like your repo and idea I have an amazing landing page with some css animation in it Will you please assign mi this issue so I can work on it and add it to your repo with readme.md file
> 
> Thank you

Yeah sure, it would be great to have your amazing contribution !
